-- MySQL Script generated by MySQL Workbench
-- dom 20 sep 2015 08:17:51 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdfarmacia
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bdfarmacia` ;

-- -----------------------------------------------------
-- Schema bdfarmacia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdfarmacia` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bdfarmacia` ;

-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbCategoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbCategoria` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbCategoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(25) NOT NULL COMMENT '',
  PRIMARY KEY (`idCategoria`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbTipoProducto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbTipoProducto` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbTipoProducto` (
  `idTipoProducto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcionTipo` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idTipoProducto`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbPresentacionProducto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbPresentacionProducto` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbPresentacionProducto` (
  `idPresentacionProducto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcionPresentacion` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idPresentacionProducto`)  COMMENT '')
ENGINE = InnoDB
COMMENT = 'biugyb';


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbUnidadMedida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbUnidadMedida` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbUnidadMedida` (
  `idUnidadMedida` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcionUnidad` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idUnidadMedida`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbProducto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbProducto` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbProducto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idCategoria` INT NOT NULL COMMENT '',
  `idTipoProducto` INT NOT NULL COMMENT '',
  `idPresentacionProducto` INT NOT NULL COMMENT '',
  `idUnidadMedida` INT NOT NULL COMMENT '',
  `descripcion` VARCHAR(60) NOT NULL COMMENT '',
  PRIMARY KEY (`idProducto`)  COMMENT '',
  INDEX `fk_tb_producto_1_idx` (`idCategoria` ASC)  COMMENT '',
  INDEX `fk_tbProducto_1_idx` (`idTipoProducto` ASC)  COMMENT '',
  INDEX `fk_tbProducto_2_idx` (`idPresentacionProducto` ASC)  COMMENT '',
  INDEX `fk_tbProducto_3_idx` (`idUnidadMedida` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_producto_1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `bdfarmacia`.`tbCategoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbProducto_1`
    FOREIGN KEY (`idTipoProducto`)
    REFERENCES `bdfarmacia`.`tbTipoProducto` (`idTipoProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbProducto_2`
    FOREIGN KEY (`idPresentacionProducto`)
    REFERENCES `bdfarmacia`.`tbPresentacionProducto` (`idPresentacionProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbProducto_3`
    FOREIGN KEY (`idUnidadMedida`)
    REFERENCES `bdfarmacia`.`tbUnidadMedida` (`idUnidadMedida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbAgenteVentas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbAgenteVentas` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbAgenteVentas` (
  `idAgenteVenta` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreAgente` VARCHAR(45) NOT NULL COMMENT '',
  `telefonoAgente` VARCHAR(45) NOT NULL COMMENT '',
  `correoAgente` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idAgenteVenta`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbTipoPago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbTipoPago` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbTipoPago` (
  `idTipoPago` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idTipoPago`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbPaciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbPaciente` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbPaciente` (
  `idPaciente` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cedula` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `apellido1` VARCHAR(45) NOT NULL COMMENT '',
  `apellido2` VARCHAR(45) NOT NULL COMMENT '',
  `direccion` VARCHAR(45) NOT NULL COMMENT '',
  `telefono` VARCHAR(45) NOT NULL COMMENT '',
  `correo` VARCHAR(45) NOT NULL COMMENT '',
  `contrasenia` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idPaciente`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbReceta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbReceta` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbReceta` (
  `idReceta` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idProducto` INT NOT NULL COMMENT '',
  `idPaciente` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idReceta`, `idProducto`, `idPaciente`)  COMMENT '',
  INDEX `fk_tbReceta_1_idx` (`idPaciente` ASC)  COMMENT '',
  CONSTRAINT `fk_tbReceta_1`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `bdfarmacia`.`tbPaciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbFactura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbFactura` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbFactura` (
  `idFactura` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idReceta` INT NOT NULL COMMENT '',
  `idTipoPago` INT NOT NULL COMMENT '',
  `cliente` INT NOT NULL COMMENT '',
  `fecha` DATE NOT NULL COMMENT '',
  `montoTotal` DOUBLE NOT NULL COMMENT '',
  PRIMARY KEY (`idFactura`, `idReceta`, `idTipoPago`)  COMMENT '',
  INDEX `fk_tb_facturacion_3_idx` (`idTipoPago` ASC)  COMMENT '',
  INDEX `fk_tbFactura_1_idx` (`idReceta` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_facturacion_3`
    FOREIGN KEY (`idTipoPago`)
    REFERENCES `bdfarmacia`.`tbTipoPago` (`idTipoPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbFactura_1`
    FOREIGN KEY (`idReceta`)
    REFERENCES `bdfarmacia`.`tbReceta` (`idReceta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbTipoUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbTipoUsuario` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbTipoUsuario` (
  `idTipoUsuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idTipoUsuario`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbPersona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbPersona` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbPersona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cedula` INT NOT NULL COMMENT '',
  `idTipoUsuario` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `apellido1` VARCHAR(45) NOT NULL COMMENT '',
  `apellido2` VARCHAR(45) NOT NULL COMMENT '',
  `direccion` VARCHAR(45) NOT NULL COMMENT '',
  `telefono` VARCHAR(45) NOT NULL COMMENT '',
  `celular` VARCHAR(45) NOT NULL COMMENT '',
  `correo` VARCHAR(45) NOT NULL COMMENT '',
  `contrasenia` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idPersona`)  COMMENT '',
  INDEX `fk_tbPersona_1_idx` (`idTipoUsuario` ASC)  COMMENT '',
  CONSTRAINT `fk_tbPersona_1`
    FOREIGN KEY (`idTipoUsuario`)
    REFERENCES `bdfarmacia`.`tbTipoUsuario` (`idTipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbProductoLote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbProductoLote` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbProductoLote` (
  `idLote` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idProducto` INT NOT NULL COMMENT '',
  `idAgenteVenta` INT NOT NULL COMMENT '',
  `concentracion` DOUBLE NOT NULL COMMENT '',
  `fechaIngreso` DATE NOT NULL COMMENT '',
  `fechaVencimiento` DATE NOT NULL COMMENT '',
  `cantidad` INT NOT NULL COMMENT '',
  `precioCompra` DOUBLE NOT NULL COMMENT '',
  `precioVenta` DOUBLE NOT NULL COMMENT '',
  PRIMARY KEY (`idLote`, `idProducto`, `idAgenteVenta`)  COMMENT '',
  INDEX `fk_tbProductoLote_1_idx` (`idProducto` ASC)  COMMENT '',
  INDEX `fk_tbProductoLote_2_idx` (`idAgenteVenta` ASC)  COMMENT '',
  CONSTRAINT `fk_tbProductoLote_1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `bdfarmacia`.`tbProducto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbProductoLote_2`
    FOREIGN KEY (`idAgenteVenta`)
    REFERENCES `bdfarmacia`.`tbAgenteVentas` (`idAgenteVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbFacturaProductos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbFacturaProductos` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbFacturaProductos` (
  `idFacturacion` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idLote` INT NOT NULL COMMENT '',
  `cantidad` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idFacturacion`, `idLote`)  COMMENT '',
  INDEX `fk_tbFacturaProductos_1_idx` (`idLote` ASC)  COMMENT '',
  CONSTRAINT `fk_tbFacturaProductos_1`
    FOREIGN KEY (`idLote`)
    REFERENCES `bdfarmacia`.`tbProductoLote` (`idLote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbDireccionCasaComercial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbDireccionCasaComercial` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbDireccionCasaComercial` (
  `idDireccionCasaComercial` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `provincia` VARCHAR(45) NOT NULL COMMENT '',
  `canton` VARCHAR(45) NOT NULL COMMENT '',
  `distrito` VARCHAR(45) NOT NULL COMMENT '',
  `otraSenias` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idDireccionCasaComercial`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbCasaComercial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbCasaComercial` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbCasaComercial` (
  `idCasaComercial` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idDireccionCasaComercial` INT NOT NULL COMMENT '',
  `nombreCasaComercial` VARCHAR(45) NOT NULL COMMENT '',
  `telefonoCasaComercial` VARCHAR(45) NOT NULL COMMENT '',
  `correoCasaComercial` VARCHAR(45) NOT NULL COMMENT '',
  `faxCasaComercial` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idCasaComercial`)  COMMENT '',
  INDEX `fk_tbCasaComercial_1_idx` (`idDireccionCasaComercial` ASC)  COMMENT '',
  CONSTRAINT `fk_tbCasaComercial_1`
    FOREIGN KEY (`idDireccionCasaComercial`)
    REFERENCES `bdfarmacia`.`tbDireccionCasaComercial` (`idDireccionCasaComercial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbEmpleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbEmpleado` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbEmpleado` (
  `cedulaEmpleado` INT NOT NULL COMMENT '',
  PRIMARY KEY (`cedulaEmpleado`)  COMMENT '',
  CONSTRAINT `fk_tbEmpleados_1`
    FOREIGN KEY (`cedulaEmpleado`)
    REFERENCES `bdfarmacia`.`tbPersona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbCliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbCliente` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbCliente` (
  `cedulaCliente` INT NOT NULL COMMENT '',
  PRIMARY KEY (`cedulaCliente`)  COMMENT '',
  CONSTRAINT `fk_tbCliente_1`
    FOREIGN KEY (`cedulaCliente`)
    REFERENCES `bdfarmacia`.`tbPersona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbCasaComercialAgente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbCasaComercialAgente` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbCasaComercialAgente` (
  `idCasaComercial` INT NOT NULL COMMENT '',
  `idAgenteVenta` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idCasaComercial`, `idAgenteVenta`)  COMMENT '',
  INDEX `fk_tbCasaComercialAgente_1_idx` (`idAgenteVenta` ASC)  COMMENT '',
  CONSTRAINT `fk_tbCasaComercialAgente_1`
    FOREIGN KEY (`idAgenteVenta`)
    REFERENCES `bdfarmacia`.`tbAgenteVentas` (`idAgenteVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbCasaComercialAgente_2`
    FOREIGN KEY (`idCasaComercial`)
    REFERENCES `bdfarmacia`.`tbCasaComercial` (`idCasaComercial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbIngredienteActivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbIngredienteActivo` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbIngredienteActivo` (
  `idIngredienteActivo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcionIngrediente` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idIngredienteActivo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbProductoIngrediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbProductoIngrediente` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbProductoIngrediente` (
  `idProducto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idIngredienteActivo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idProducto`, `idIngredienteActivo`)  COMMENT '',
  INDEX `fk_tbProductoIngrediente_1_idx` (`idIngredienteActivo` ASC)  COMMENT '',
  CONSTRAINT `fk_tbProductoIngrediente_1`
    FOREIGN KEY (`idIngredienteActivo`)
    REFERENCES `bdfarmacia`.`tbIngredienteActivo` (`idIngredienteActivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbProductoIngrediente_2`
    FOREIGN KEY (`idProducto`)
    REFERENCES `bdfarmacia`.`tbProducto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbSintoma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbSintoma` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbSintoma` (
  `idSintoma` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcionSintoma` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idSintoma`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbEnfermedad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbEnfermedad` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbEnfermedad` (
  `idEnfermedad` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreCientifico` VARCHAR(45) NOT NULL COMMENT '',
  `nombreComun` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idEnfermedad`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbEntrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbEntrega` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbEntrega` (
  `idEntrega` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idFactura` INT NOT NULL COMMENT '',
  `estadoEntrega` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idEntrega`, `idFactura`)  COMMENT '',
  INDEX `fk_tbEntrega_1_idx` (`idFactura` ASC)  COMMENT '',
  CONSTRAINT `fk_tbEntrega_1`
    FOREIGN KEY (`idFactura`)
    REFERENCES `bdfarmacia`.`tbFactura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbMetodoAplicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbMetodoAplicacion` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbMetodoAplicacion` (
  `idMetodoAplicacion` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcionAplicacion` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idMetodoAplicacion`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbProductoSintoma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbProductoSintoma` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbProductoSintoma` (
  `idProducto` INT NOT NULL COMMENT '',
  `idSintoma` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idProducto`, `idSintoma`)  COMMENT '',
  INDEX `fk_tbProductoSintoma_2_idx` (`idSintoma` ASC)  COMMENT '',
  CONSTRAINT `fk_tbProductoSintoma_1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `bdfarmacia`.`tbProducto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbProductoSintoma_2`
    FOREIGN KEY (`idSintoma`)
    REFERENCES `bdfarmacia`.`tbSintoma` (`idSintoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbProductoAplicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbProductoAplicacion` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbProductoAplicacion` (
  `idProducto` INT NOT NULL COMMENT '',
  `idMetodoAplicacion` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idProducto`, `idMetodoAplicacion`)  COMMENT '',
  INDEX `fk_tbProductoAplicacion_2_idx` (`idMetodoAplicacion` ASC)  COMMENT '',
  CONSTRAINT `fk_tbProductoAplicacion_1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `bdfarmacia`.`tbProducto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbProductoAplicacion_2`
    FOREIGN KEY (`idMetodoAplicacion`)
    REFERENCES `bdfarmacia`.`tbMetodoAplicacion` (`idMetodoAplicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbProductoReceta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbProductoReceta` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbProductoReceta` (
  `idProducto` INT NOT NULL COMMENT '',
  `idReceta` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idProducto`, `idReceta`)  COMMENT '',
  INDEX `fk_tbProductoReceta_2_idx` (`idReceta` ASC)  COMMENT '',
  CONSTRAINT `fk_tbProductoReceta_1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `bdfarmacia`.`tbProducto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbProductoReceta_2`
    FOREIGN KEY (`idReceta`)
    REFERENCES `bdfarmacia`.`tbReceta` (`idReceta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfarmacia`.`tbEnfermedadSintoma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfarmacia`.`tbEnfermedadSintoma` ;

CREATE TABLE IF NOT EXISTS `bdfarmacia`.`tbEnfermedadSintoma` (
  `idEnfermedad` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idSintoma` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idEnfermedad`, `idSintoma`)  COMMENT '',
  INDEX `fk_tbEnfermedadSintoma_1_idx` (`idSintoma` ASC)  COMMENT '',
  CONSTRAINT `fk_tbEnfermedadSintoma_1`
    FOREIGN KEY (`idSintoma`)
    REFERENCES `bdfarmacia`.`tbSintoma` (`idSintoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbEnfermedadSintoma_2`
    FOREIGN KEY (`idEnfermedad`)
    REFERENCES `bdfarmacia`.`tbEnfermedad` (`idEnfermedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
